CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    sender_name VARCHAR(64) NOT NULL,
    sender_phone VARCHAR(20) NOT NULL,
    sender_address VARCHAR(256) NOT NULL,
    sender_lng DECIMAL(10,6) NOT NULL,
    sender_lat DECIMAL(10,6) NOT NULL,
    receiver_name VARCHAR(64) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    receiver_address VARCHAR(256) NOT NULL,
    receiver_lng DECIMAL(10,6) NOT NULL,
    receiver_lat DECIMAL(10,6) NOT NULL,
    goods_name VARCHAR(128),
    weight DECIMAL(8,2),
    volume DECIMAL(8,2),
    status VARCHAR(20) NOT NULL,
    remark VARCHAR(1024),
    creator_id BIGINT NOT NULL,
    deleted SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_creator ON orders(creator_id);
CREATE INDEX idx_orders_created_at ON orders(created_at);
