CREATE TABLE order_chat_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE order_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_order_chat_messages_conversation FOREIGN KEY (conversation_id)
        REFERENCES order_chat_conversations(id)
);

CREATE INDEX idx_chat_conversations_order_id ON order_chat_conversations(order_id);
CREATE INDEX idx_chat_messages_conversation_id ON order_chat_messages(conversation_id);
CREATE INDEX idx_chat_messages_created_at ON order_chat_messages(created_at);
